[DEFAULT]

subsuite = "enterprise"

["test_felt_browser_about_config_blocked.py"]

["test_felt_browser_console_error.py"]

["test_felt_browser_context_menu.py"]

["test_felt_browser_crash_abort_restart.py"]

["test_felt_browser_crash_restart.py"]

["test_felt_browser_exit_tokens.py"]

["test_felt_browser_external_link.py"]

["test_felt_browser_fxa.py"]

["test_felt_browser_new_window_from_cli.py"]

["test_felt_browser_restart_is_quit.py"]

["test_felt_browser_restart_works.py"]

["test_felt_browser_safe_mode.py"]

["test_felt_browser_shutdown_crash_exit.py"]

["test_felt_browser_signout.py"]

["test_felt_browser_signout_verify.py"]

["test_felt_browser_starts.py"]

["test_felt_device_posture.py"]

["test_firefox_start.py"]
